# Generated by Django 5.0.6 on 2024-09-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
