# Generated by Django 5.0.6 on 2024-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_monument_address_alter_monument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
