# Generated by Django 5.0.6 on 2024-09-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_monument_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='monument',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='name',
            field=models.TextField(),
        ),
    ]
